#!/bin/bash
set -xe
branches='trunk trunk-mem-api'
eval "$@"
if [ -n "$build" ]
then
export CFLAGS='-O2 -I/opt/local/include' LDFLAGS='-L/opt/local/lib' 
for branch in $branches
do
  prefix=$HOME/local/ruby-${branch}
  ruby=$prefix/bin/ruby

  git checkout $branch
  (
      mkdir -p $prefix
      ./configure --prefix=$prefix 
      make
      make install
  ) >$branch.build.log 2>&1 || exit 1
  make test >/dev/null 2>&1
  time ( make test >/dev/null 2>&1) 
  time ( make test >/dev/null 2>&1) 
done
fi

if [ -n "$run" ]
then
for branch in $branches
do
  prefix=$HOME/local/ruby-${branch}
  ruby=$prefix/bin/ruby

  time $ruby -e '
x = [ nil ]
10000000.times do | i |
  x[0] = [ i ]
  x = x[0]
end
puts :OK
system "ps -l -p #{$$}"
'
done
fi


